FROM quay.io/jupyterhub/jupyterhub


RUN pip install --no-cache-dir \
    dockerspawner \
    jupyterhub-dummyauthenticator 

    
# CMD ["jupyterhub","--config","/srv/jupyterhub/jupyterhub_config.py"]



