FROM quay.io/jupyterhub/jupyterhub:latest

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir \
    dockerspawner \
    oauthenticator \
    jupyter-server-proxy \
    jupyterhub-idle-culler \
    && rm -rf /root/.cache/pip
    
# CMD ["jupyterhub","--config","/srv/jupyterhub/jupyterhub_config.py"]



