services:
    single-jupyter:
      build: .
      image: single-jupyter
      ports:
        - 8888:8888
      volumes:
        - ./notebooks:/home/jovyan/notebooks
        - ./data:/home/jovyan/data
      environment:
        - JUPYTER_ENABLE_LAB=yes
      command: >
        start-notebook.sh
        --NotebookApp.token=''
        --ServerApp.disable_check_xsrf='True' 
        --ServerApp.trust_xheaders='True'